version: '3.9'

services:
  web:
    build:
      context: .
    image: goam_image
    # '/start' is the shell script used to run the service
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine